### ISSUE TITLE
Multiplayer Notice

### ISSUE THREAD

**Issue by tay-clark** [KyleMMoore/DiceRoll#1]
In Multiplayer, when a user rolls a dice, other players are unable to see it.

Additionally, the default # of dice rolled is 7. This should be 1, allowing users to specify if multiple dice should be rolled.

**Comment by KyleMMoore** [comment]
Fixed the issue involving other players not seeing the dice roll message, though it appears to only be a problem when rolling a single dice i.e. /roll <dice>

That said, I'm having a hard time replicating the issue with rolling 7 dice by default.

**Comment by KyleMMoore** [comment]
Closing the issue until confirmation that the issue is reoccurring.
